apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-image
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits: 
            memory: "700Mi"
            cpu: "600m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql
                key: password
        - name: MYSQL_DATABASE
          valueFrom:
              secretKeyRef:
                name: mysql
                key: tabela
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress-deployment
  replicas:  2
  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: wordpress-deployment
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress-image
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits: 
            memory: "700Mi"
            cpu: "600m"
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-user-secret
                key: password
        - name: WORDPRESS_DB_NAME
          value: stefanini
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
spec:
  selector:
    matchLabels:
      app: adminer-deployment
  replicas:  1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adminer-deployment
    spec:
      containers:
      - image: adminer:latest
        name: adminer-image
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits: 
            memory: "200Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
          name: adminer
