version: "3"
services:
   db:
     image: mysql:latest
     volumes:
       - db_dados:/var/lib/mysql
     restart: always
     #ports: para testa diretamente na maquina host
     # - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: my-secret-pw
       MYSQL_DATABASE: stefanini
       MYSQL_USER: stefanini
       MYSQL_PASSWORD: stefanini
     networks:
       - rede-a
   adminer:
     depends_on:
       - db
     image: adminer:latest
     restart: always
     ports:
       - 8080:8080
     networks:
       - rede-a
volumes:
     db_dados: {}
#  docker network create --drive bridge nome-rede
networks: 
  rede-a:
    driver: bridge
    ipam: 
     config:
     - subnet: 192.192.203.192/27
