#kubectl expose deployment mysql-deployment --type=LoadBalancer --port=3306
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: LoadBalancer
  selector:
    app: mysql-deployment
  ports:
  - port: 3306
