#arquivo não funcionando usei enquanto isso a linha de comando
#kubectl expose deployment mysql-deployment --type=LoadBalancer --port=3306
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: LoadBalancer
  ports:
  - port: 3306
  selector:
    app: mysql-deployment